const fs = require('fs');
let content = fs.readFileSync('assets/i18n.js', 'utf8');

// Remove ALL entries generated by our scripts (cases 02-06, and duplicate keys for 01,07)
// They have format: cXX-sXX-XXX-N or cXX-sXX-XXXN
const badKeyRegex = /^\s+'c0[2-6]-s\d+-[a-z]+-\d+'/m;
const badKeyRegex01 = /^\s+'c01-s6-h3-[4-9]'/m;
const badKeyRegex07 = /^\s+'c07-s6-h3-[4-9]'/m;

let prevLength;
do {
  prevLength = content.length;
  content = content.replace(badKeyRegex, '');
  content = content.replace(badKeyRegex01, '');
  content = content.replace(badKeyRegex07, '');
} while (content.length !== prevLength);

// Also remove any empty line blocks
content = content.replace(/\n{3,}/g, '\n\n');

// Also remove any duplicate empty lines
content = content.replace(/\n\n\n/g, '\n\n');

fs.writeFileSync('assets/i18n.js', content, 'utf8');
console.log('Restored i18n.js');
